apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudtxn-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudtxn-demo
  template:
    metadata:
      labels:
        app: cloudtxn-demo
    spec:
      containers:
        - name: nginx
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
